# Generated by Django 2.0.6 on 2018-06-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0004_mycart_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='image',
        ),
    ]
