# Generated by Django 2.0.6 on 2018-06-28 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eco', '0005_remove_mycart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='userId',
        ),
        migrations.AddField(
            model_name='mycart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mycart',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
