# Generated by Django 2.0.6 on 2018-07-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0006_auto_20180628_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
