# Generated by Django 2.0.6 on 2018-07-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0007_mycart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
