# Generated by Django 2.0.6 on 2018-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0008_auto_20180702_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='productId',
            field=models.IntegerField(default=0),
        ),
    ]
