# Generated by Django 2.0.6 on 2018-07-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0009_mycart_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='productId',
        ),
    ]
