# Generated by Django 2.0.6 on 2018-07-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0010_remove_mycart_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='productId',
            field=models.IntegerField(default=0),
        ),
    ]
