# Generated by Django 2.0.6 on 2018-07-09 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0011_mycart_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mycart', to=settings.AUTH_USER_MODEL),
        ),
    ]
