# Generated by Django 2.0.7 on 2018-07-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0012_auto_20180709_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
