# Generated by Django 2.0.7 on 2018-07-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0017_auto_20180711_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
    ]
