# Generated by Django 2.0.6 on 2018-07-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0019_auto_20180711_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
